### ISSUE TITLE
Missing menupoints for Profile and Terminology (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-ppqm#14] opened 2022-09-29 14:09 UTC
ch.fhir.ig.ch-epr-ppqm#0.2.0 /

The IG has only menu Home/Artifacts but there are also Profiles, CodeSystems and ValueSets defined in the IG.
Normally there are Menu Entries for that to finde faster the profiles or codes.

Roeland Luykx (RALY GmbH)

**Comment by unixoid** [comment] 2022-10-16 14:50
Duplicate of #8.

**Closed as not planned by unixoid** 2022-10-16 14:50 UTC
