### ISSUE TITLE
QA: error through dependency (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [ehealthsuisse/ch-epr-ppqm#11] opened 2022-09-10 09:04 UTC
I am aware that an issue from QA is not from IG itself, but exists through a dependency (I don't know which of the issues below). Could the error message be captured as 'suppressed message' (even if it is not suppressed) and as a GitHub issue so that it is apparent that the issue is known? And clean up the other one.

* A code with no system has no defined meaning. A system should be provided
* if identifier.system is ''urn:ietf:rfc:3986'', then the identifier.value must be a full URI (e.g. start with a scheme)

**Comment by unixoid** [comment] 2022-10-16 17:58
I did not manage to suppress error messages via ignoreWarnings.txt -- probably because they are errors and not warnings.

**Comment by ziegm** [comment] 2022-10-18 07:07
Why do these codes have no system? Could that be fixed?

```
== Suppressed Messages ==

# (Explanation, why there is no system)
A code with no system has no defined meaning. A system should be provided

# As information: Error from the base specification
if identifier.system is ''urn:ietf:rfc:3986'', then the identifier.value must be a full URI (e.g. start with a scheme)
```

**Comment by unixoid** [comment] 2022-10-24 07:17
Suppression of error messages does not work, but I fixed the cause of the warnings.
I propose to close this ticket.

**Comment by ziegm** [comment] 2022-10-25 06:22
Errors cannot be suppressed.
You could just put it in QA (then the error appears anyway) that others know that this error is known and has nothing to do with this IG.

**Comment by unixoid** [comment] 2022-10-30 12:55
Hope everything looks good now :-)

**Closed as completed** 2023-06-30 13:19 UTC
